### PR TITLE
rebar.config: Bump Ranch version to 1.4.0

### PR DESCRIPTION
**Pull request by dumbbell**
According to Loïc Hoguin, Ranch was not changed in incompatible way for a long time, so 1.4.0 should be a drop-in replacement.

### CODE REVIEW

**Comment by dumbbell** [comment]
If you accept this pull request, could you please publish a new version to Hex.pm?

**Comment by ypaq** [comment]
Thanks!

**Comment by ypaq** [comment]
Uploaded to hex.

**Comment by michaelklishin** [comment]
@ypaq thank you.

**Pull request merged**
