### PR TITLE
Use Ranch 1.6.1 + restore Erlang 19/20 compatibility

### PR DESCRIPTION
**Pull request by dumbbell**
Hi!

In RabbitMQ, we would like to upgrade Ranch to 1.6.0. This new version requires a new callback for transport modules, `handshake/3`. I prepared a patch (first commit in the branch) to add it. The testsuite passes, however, I'm not 100% confident about the implementation (I mostly looked at what was done in Ranch transport modules).

The second commit in the branch restores Erlang 19.x and Erlang 20.x support: those versions don't have `ssl:handshake/3`. Again, I don't know if this kind of runtime check is ok with you, but we would like to keep support for Erlang 19+ in RabbitMQ.

Thank you!

### CODE REVIEW

**Comment by dumbbell** [comment]
Done!

**Comment by doughsay** [comment]
Any reason this hasn't been merged yet? Looking forward to having this fix live...

**Comment by michaelklishin** [comment]
@getong anything else you'd like to be changed here? This is a pretty important PR for RabbitMQ as we cannot upgrade Ranch and support the OTP versions we support in the current GA release series without it.

**Comment by michaelklishin** [comment]
@ypaq sorry to ping you directly but this PR has been sitting there for 3 weeks now.

**Comment by getong** [comment]
I think it is ok to merge.

**Comment by michaelklishin** [comment]
If the maintainers of this project are busy with other things, can it be transferred to the Ranch or RabbitMQ orgs, both of which have a lot of vested interest in not letting this project rot?

A major issue with a pretty small PR and surface area hasn't been addressed in almost a month after several pings. Time to hand the project over to those who care about it more?

**Comment by michaelklishin** [comment]
@ypaq ping, please take a look at this PR, it is critically important to RabbitMQ's Proxy protocol support. We would really like not to run a fork again.

**Comment by dumbbell** [comment]
FYI, in the absence of any feedback, I just published the branch in this pull request as version 2.1.0-rc.1 on Hex.pm. It's a pre-release so I believe users won't get it out-of-the-box and we (the RabbitMQ team) and other people wanting Ranch 1.6.x can move forward.

**Comment by ypaq** [comment]
Apologies for the delay. The notification emails for this repo fall through the cracks on my end. We can talk about forking and hex.pm access if you think turn-around time is a serious problem.

**Comment by michaelklishin** [comment]
@ypaq we don't have to fork if you'd be open to adding more collaborators (and perhaps an owner, if Heroku permits) to this repo from the user community. I wonder if it should be a Nine Nines project next to Ranch. Not sure if @essen would be open to that :)

**Pull request merged**
